# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Created: 16-07-2017 12:51
# Licence: GPLv3 - General Public Licence version 3

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:contact }