
home:
    path:     /home
    defaults: { _controller: AppBundle:Home:home }

camping_site:
    path:     /campingSite
    defaults: { _controller: AppBundle:Home:campingSite }

apartment:
    path:     /apartment
    defaults: { _controller: AppBundle:Home:apartment }

prices:
    path:     /prices
    defaults: { _controller: AppBundle:Home:prices }

joris:
    path:     /joris
    defaults: { _controller: AppBundle:Home:joris }
